# Generated by Django 3.2 on 2022-12-13 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0003_employee_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_profile',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
    ]
